version: '3'
services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: moodle-db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_USER=moodle_user
      - MARIADB_PASSWORD=moodle_password
      - MARIADB_DATABASE=moodle
    volumes:
      - mariadb_data:/bitnami/mariadb

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle-app
    restart: always
    environment:
      - MOODLE_DATABASE_HOST=moodle-db
      - MOODLE_DATABASE_USER=moodle_user
      - MOODLE_DATABASE_PASSWORD=moodle_password
      - MOODLE_DATABASE_NAME=moodle
    ports:
      - "8080:8080"
    volumes:
      - moodle_data:/bitnami/moodle
      - moodle_app_data:/bitnami/moodledata

volumes:
  mariadb_data:
  moodle_data:
  moodle_app_data:
